### ISSUE TITLE
checking of answers and untis not independent

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/scooter#100]
If you choose the correct unit but leave the number box empty then both boxes return incorrect even if the unit is correct.  Can they be checked independently?  In the screenshot below "s" is correct but is marked incorrect because there is nothing in the number box.  Students might want to check their units first?

![image](https://cloud.githubusercontent.com/assets/5931508/4433987/4b5ceea0-46fb-11e4-9050-2cc9a2a3b1e1.png)

**Comment by daviesian** [comment]
This should be raised on ucam-cl-dtg/isaac-app.
