### ISSUE TITLE
ID field for content block

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/scooter#106]
Issue found in 3aa3355b83e800980c602cfab5f1548b15f81d0f

It would be really useful if we could easily add an ID to a block of content. I am going through deep-linking the concepts and questions and it is slow going having to read through the json and find which block of text it is you wanted and so on. If in the first instance you could add IDs to an accordion section, that would already be a huge help!

**Comment by daviesian** [comment]
Fixed in 61203403e01e3e19ee62e2f285be4e8fc9143f29.
