### ISSUE TITLE
Video caption

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/scooter#108]
Issue found in 3aa3355b83e800980c602cfab5f1548b15f81d0f

The caption inserted next to a video in the editor does not appear on the site. It would be useful to be able to add metadata, similar to figures, but I don't think we need a title as figures do, but it would be useful to display a caption if someone has written one.

**Comment by daviesian** [comment]
Good thinking. We don't have designs for that at the moment, but I can try to come up with something. In any case, an issue for ucam-cl-dtg/isaac-app.
