### ISSUE TITLE
Units not being marked independently of number

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/scooter#109]
Issue found in 3aa3355b83e800980c602cfab5f1548b15f81d0f

On this question the units are being marked wrong even when they are right if the numerical answer is wrong.

I.e. "m" is marked wrong if 4.0 or 4.1 is entered as an answer.  if 4.4 m is entered then the whole things is marked correct

<Describe issue here>

**Comment by daviesian** [comment]
This is an issue for isaac-app.
