### ISSUE TITLE
Need to be able to create events and support things like locations / date entry (that converts to Long(int) format)

### ISSUE THREAD

**Issue by sacummins** [ucam-cl-dtg/scooter#113]

**Comment by daviesian** [comment]
Date now supported. Location doesn't seem to be in use yet.

**Comment by jsharkey13** [comment]
Location is in use, and has to be entered by hand like this:
![image](https://cloud.githubusercontent.com/assets/8060558/10731264/75cd608a-7bec-11e5-9b05-d65e78231bf3.png)

**Comment by daviesian** [comment]
Well spotted. Now supported.
