### ISSUE TITLE
Content blocks render with different amounts of inset even though they are entered in the same way

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/scooter#116]
Issue found in 166936d3b298a293d4ddd2e573cadc3489ce5f38

Below is a screen shot of two accordions that both have a right aligned image but the text of the first is indented more than the text of the second.  

This is often an issue, even if there is just text, but I haven't been able to identify why.

<Describe issue here>
![image](https://cloud.githubusercontent.com/assets/5931508/7140601/19b72d38-e2c4-11e4-9a1f-80dabf5e08d6.png)

**Comment by daviesian** [comment]
This was an issue in ucam-cl-dtg/isaac-app, which I believe is now fixed.
