### ISSUE TITLE
Report Issue Links Hidden Under Content

### ISSUE THREAD

**Issue by vp341** [ucam-cl-dtg/scooter#118]
Issue found in 91e0c129815926aa4b6b2f1827091dc43f46b05b

For questions in the content editor, the report issue buttons are hidden by the content itself. 

![image](https://cloud.githubusercontent.com/assets/12997033/8302469/722e0436-198e-11e5-9cb7-1a54606a1a08.png)

**Comment by daviesian** [comment]
I can live with this.
