### ISSUE TITLE
Exposition Disappears.

### ISSUE THREAD

**Issue by vp341** [ucam-cl-dtg/scooter#119]
Issue found in 91e0c129815926aa4b6b2f1827091dc43f46b05b

When adding a new part of a question, if nothing is written in the exposition, but you click done by accident then the whole exposition section disappears and is  not retrievable.

**Comment by mjc209** [comment]
It is still there, and I seem to be able to get it back by clicking in-between the two crosses where it was

**Comment by vp341** [comment]
Ah - got it, thanks!
