### ISSUE TITLE
Table Bug!

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/scooter#120]
Unclosed table tags cause catastrophic formatting errors:

![image](https://cloud.githubusercontent.com/assets/8060558/9065427/46863bd0-3ac9-11e5-83cf-2df65973010b.png)

Discovered by Michael accidentally; I narrowed it down to being a missing <\table> in a HTML table present on the page.

The best example is: http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/general_pages/book/ch_d_p8.json and deleting the last <\table> tag, saving, and then reloading and clicking on sections causes some really quite impressive formatting disasters. Editing other pages without clearing the cache causes similar issues on those pages even without tables. Clearing the cache fixes the issue except on the broken page . . .

**Comment by daviesian** [comment]
Not fixable. If you break HTML, HTML is broken ;-)
