### ISSUE TITLE
Problems with figure references and underscores

### ISSUE THREAD

**Issue by dl495** [ucam-cl-dtg/scooter#122]
When there are underscores in figure IDs (as per Wiki instruction), \ref{ [figure_id] } will render on staging as "Figure ", i.e. without a number next to it.

Working figure references example: content/concepts/maths/functions_trigonometric.json
Broken figure references example: content/concepts/maths/graph_sketching.json

@jsharkey13 

![screen shot 2015-08-14 at 12 07 46](https://cloud.githubusercontent.com/assets/7312416/9272713/29775ba8-427d-11e5-8bae-b2871428c7ec.png)

![screen shot 2015-08-14 at 12 07 59](https://cloud.githubusercontent.com/assets/7312416/9272716/2e2f923c-427d-11e5-8c77-17d45c606429.png)

**Comment by jsharkey13** [comment]
@sacummins or @daviesian - have references changed since last summer, or are there any known issues?

**Comment by jsharkey13** [comment]
I think this is the main issue: https://github.com/ucam-cl-dtg/isaac-app/issues/410

and the scooter version isn't actually the problem.
