### ISSUE TITLE
isaacFastTrackQuestionPage can't "View on Staging"

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/scooter#124]
Can't just click button to view on staging despite fact that the location behaves exactly as an isaacQuestionPage would.

**Comment by jsharkey13** [comment]
Similar to #121, this needs to link to `/questions/[id]`
and the other one needs to link to `/events/[id]`

**Comment by daviesian** [comment]
Fixed in ddd8e3ad22b6b7b28f27f69b31499c6fdd5c4471.
