### ISSUE TITLE
Inability to Spell Check on Editor

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/scooter#125]
The current content boxes used by the editor are not compatible with Chrome's built in spell-check; this has led to quite a large number of errors on the site; many more may exist. Is it possible to fix the boxes to allow spell-checking to work?

**Comment by daviesian** [comment]
This is sufficiently hard that it's not going to happen any time soon. The editor is CodeMirror, which doesn't support spell check.

**Comment by jsharkey13** [comment]
Can you not make the text boxes recognisable to a browser as a textbox; and rely on decent browsers inbuilt spell-checkers? Chrome spellchecks anything it recognises as a textbox, but it doesn't recognise the boxes of the editor (except the metadata fields).

**Comment by daviesian** [comment]
They are not textboxes. They are entirely custom components created by CodeMirror to look like textboxes - take a look at the inspector. If you can get spell checking working with CodeMirror under RequireJS I will happily integrate it.
