### ISSUE TITLE
tab (vi) shows up as (v)

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/scooter#127]
Issue found in 91e0c129815926aa4b6b2f1827091dc43f46b05b

We have labelled at tab vi in the editor and it is rendering on the site as v.

http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/questions/maths/workbook/fc5_comp_func.json

<Describe issue here>

**Comment by jsharkey13** [comment]
It shows up as `vi` for me? 
![image](https://cloud.githubusercontent.com/assets/8060558/9719781/de579942-557f-11e5-9481-09873656615d.png)

**Comment by mjc209** [comment]
I just changed this as it was v in the editor before. It probably just hadn't changed for you yet
