### ISSUE TITLE
Wierd table behaviour in editor. Duplicating a table that is only entered once

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/scooter#95]
Issue found in 31e99e65e94ce6f485213f7ee5cb311526a2c9f4

Text for the first table is just entered once but when you click done it appears as two tables ?

<Describe issue here>
![image](https://cloud.githubusercontent.com/assets/8695925/4215899/5da429a6-38d3-11e4-8374-53ce4d9d8c58.png)

![image](https://cloud.githubusercontent.com/assets/8695925/4215902/6ba4c34e-38d3-11e4-83ec-b5d992e081a7.png)

**Comment by daviesian** [comment]
Fixed in 5d2c88250a535dbac727d73e31186e699329d6e0.
