### ISSUE TITLE
published content not appearing as published

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/scooter#97]
Issue found in 31e99e65e94ce6f485213f7ee5cb311526a2c9f4

All of the physics concepts (this may be true as well for maths concepts, I just haven't checked) are marked as unpublished on dev and staging, when they are actually published in the editor. Also, I don't think modifications to the concepts are being pushed to the live site. I know that I modified the Friction concept page two weeks ago and that you pushed to the live site since then, but the changes haven't appeared on the live site. This is rather worrying as there are mistakes on that page on the live site which have been corrected on staging.

**Comment by daviesian** [comment]
Fixed in isaac-app.
