### ISSUE TITLE
Numeric Question - Significant Figure box - Input Validation!

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/scooter#98]
The "Significant Figures" box allows any sort of input; from large numbers: 9000, say; to negative numbers, -5; and even real numbers; 3.14159. (You can even enter text; like "hello")
Clearly you can't have pi significant figures; can we make the box validate the input?

It won't ever be outside the range [1,9] so maybe enforcing this is best?

Or checking for this on the content error page?

**Comment by daviesian** [comment]
This already shows up on the content error page.
